"""empty message

Revision ID: 7d2506e99044
Revises: d96e124e9069
Create Date: 2021-09-23 15:26:27.546883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2506e99044'
down_revision = 'd96e124e9069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regioes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('numero_estados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.add_column('estados', sa.Column('regiao_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'estados', 'regioes', ['regiao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estados', type_='foreignkey')
    op.drop_column('estados', 'regiao_id')
    op.drop_table('regioes')
    # ### end Alembic commands ###
