"""empty message

Revision ID: a58733f8a705
Revises: 7d2506e99044
Create Date: 2021-09-23 15:37:33.962298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58733f8a705'
down_revision = '7d2506e99044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bacias_hidrograficas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('bacias_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bacia_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bacia_id'], ['bacias_hidrograficas.id'], ),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bacias_estados')
    op.drop_table('bacias_hidrograficas')
    # ### end Alembic commands ###
